### PR TITLE
release version 0.3.22 for sbt-org-policies 0.9.0

### PR DESCRIPTION
**Pull request by pepegar**

### CODE REVIEW

**Review by diesalbla — APPROVED** [review]

**Comment by juanpedromoreno** [comment]
Sorry, I'm late but perhaps the `0.4.0` was the correct version, taking into account the binary compatibilities, thoughts?

**Comment by pepegar** [comment]
I've stopped the build in travis to avoid releasing an incorrect version.

If we're using semver, absolutely, my fault!  However, given that this plugin basically handles versions of other plugins, I think it's _hard_ to keep up with semver acceptable versions (basically because each minor bump on a dependency would mean a minor bump here, and each major a major here too...)

In any case, I'm open to change the version!

**Comment by juanpedromoreno** [comment]
Makes sense 👍

**Comment by pepegar** [comment]
Cool, restarting build then!

**Pull request merged**
